-- Pre-Launch Tracking Fix - the GHL /start landing page
-- (pickyourpuppylive.com) is a SEPARATE domain from the main website
-- (thepuppyplugs.com), so the existing pp_av/pp_as cookies (see
-- supabase/024_website_analytics.sql) cannot travel between them - a
-- browser never sends one domain's cookies to another. This adds a
-- small, independent tracking model for that landing page, plus one
-- column linking a website visitor back to the landing visitor who
-- sent them here.
--
-- "Landing Visitors" on the Business Dashboard previously (incorrectly)
-- counted ANY website session (lib/analytics/queries.ts
-- getFunnelDataForRange, reading analytics_sessions) - i.e. generic
-- thepuppyplugs.com traffic, not actual pickyourpuppylive.com/start
-- visitors. This migration is what makes the real definition possible;
-- the dashboard/query-layer fix is a separate (non-SQL) code change.

-- ---------------------------------------------------------------------
-- landing_visitors - one row per unique visitor to
-- pickyourpuppylive.com/start, identified by a client-generated id
-- (localStorage-based, NOT a cookie - see the GHL tracking snippet).
-- Mirrors analytics_visitors' own shape (id/first_seen_at/last_seen_at)
-- but is intentionally a SEPARATE table: this id is generated by a
-- less-trusted script running on a domain we don't control the
-- deployment of, so it is never merged into analytics_visitors directly
-- (no FK from this table out to anything).
--
-- utm_*/fbclid are first-touch only - captured once at insert, never
-- overwritten by a later visit from the same landing visitor id (same
-- philosophy as analytics_sessions.utm_* being captured once per
-- session and never updated afterward).
--
-- Verification/test rows (created via /start?pp_test=1, see the GHL
-- snippet) get an id prefixed "test_" - lib/analytics/queries.ts
-- excludes that prefix from every Landing Visitors/Landing Page Views
-- count, and they can be bulk-removed with:
--   delete from landing_page_events where landing_visitor_id like 'test_%';
--   delete from landing_visitors where id like 'test_%';
-- ---------------------------------------------------------------------
create table if not exists landing_visitors (
  id text primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),

  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  fbclid text
);

alter table landing_visitors enable row level security;

create index if not exists landing_visitors_first_seen_idx on landing_visitors (first_seen_at);

-- ---------------------------------------------------------------------
-- landing_page_events - raw (non-deduplicated) page-view log for the
-- landing page. "Landing Page Views" in the admin UI is a count of
-- these rows; "Landing Visitors" is a count of DISTINCT rows in
-- landing_visitors instead - a refresh of /start adds a row here but
-- never a new landing_visitors row (see app/api/analytics/landing-track/route.ts).
-- ---------------------------------------------------------------------
create table if not exists landing_page_events (
  id bigserial primary key,
  landing_visitor_id text not null references landing_visitors (id) on delete cascade,
  landing_session_id text,
  path text not null default '/start',
  occurred_at timestamptz not null default now()
);

alter table landing_page_events enable row level security;

create index if not exists landing_page_events_occurred_idx on landing_page_events (occurred_at);
create index if not exists landing_page_events_visitor_idx on landing_page_events (landing_visitor_id);

-- ---------------------------------------------------------------------
-- The cross-domain handoff relationship: which GHL landing visitor sent
-- this website visitor here. Nullable (most website visitors never came
-- from the GHL funnel), set at most once - first-write-wins, see
-- app/api/analytics/landing-handoff/route.ts - and deliberately NOT a
-- foreign key to landing_visitors, same reasoning as
-- inquiries.analytics_visitor_id having no FK to analytics_visitors
-- (supabase/029_inquiry_analytics_attribution.sql): a stale or forged
-- value must never be able to break website visitor tracking, which is
-- on the critical path for every single page view on the site.
-- ---------------------------------------------------------------------
alter table analytics_visitors add column if not exists landing_visitor_id text;

create index if not exists analytics_visitors_landing_visitor_idx
  on analytics_visitors (landing_visitor_id) where landing_visitor_id is not null;
